version: '3.1'

services:
  app:
    image: embraslabs/ruby:3.0.0
    container_name: pessoas-api
    user: labs:labs
    stdin_open: true
    tty: true
    ports:
      - 3010:3000
    volumes:
      - .:/project
      - gems:/.gems
    environment:
      - SECRET_KEY_BASE=development
      - RAILS_ENV=development
      - PORT=3000
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    env_file:
      - .env

volumes:
  gems: